### ISSUE TITLE
Please add feature to configure the JConsole

### ISSUE THREAD

**Issue by Chris2011** [fungl164/JConsole#2]
I really wanted this feature build in netbeans to use a command shell what I want. Cmd, powershell, cygwin or babun. For now I use babun out of netbeans, inside ConEmu. What I would like to see that I can configure the JConsole window inside the options, like the terminal window, with colors, fonts etc. AND to change the command line tool, to add cmd, powershell, cygwin or whatever I want. I know the module is 2 years old but it would be very great if we can have this.

Regards

Chris

**Comment by fungl164** [comment]
Hi Chris,

The easy answer is that you can always invoke other shells from the command line.  :)

It's been a while since I've used Netbeans, Swing and/or Windows, but things like changing fonts, text color, startup shell, etc. should be straight forward.  Advanced coloring schemes, on the other hand, might not...

If you and/or other people you know would like to get involved in design and coding, I'd be happy to work on this with you guys as time permits.  I'm happy to hear this little project is reaching out to some folks such as yourself.

Thanks for the message!  

Best,

Luis

**Comment by Chris2011** [comment]
Hi,

the problem is, that I can't invoke an other shell inside JConsole, when I try it, it opens a extra new window and this is not what I want. I wanted to change the console inside JConsole to this what I want. I had a look in your code and I saw that you have set the commandline hardcoded to cmd. And the properties too. What I would like to see, what I think that this is better, an option for jconsole to set the command line and the parameters so then I will be flexible and maybe we can see colors because of the other implementations. The color things I thought smth like the output options or the terminal options. Atm I have a lot other projects which I would like to maintain and so on so for this plugin I'm only a user ;)

Regards

Chris

**Comment by Chris2011** [comment]
Anything new? The option to open a shell like babun or cmd or powershell as an external shell is not an option for me, then I don't need those plugin. I need the option to open an other shell right now inside JConsole, and this is not possible atm for my windows. Or I forgot to activate an option or whatever.

**Comment by Chris2011** [comment]
@fungl164 plugin not alive anymore?

**Comment by Chris2011** [comment]
Because of not using this plugin anymore, I will close this ticket. And the plugin seems dead btw. Thx anyway.

**Comment by Chris2011** [comment]
To bring it up again @fungl164 I can't use another shell inside of JConsole. I'm using windows 10 and I tried to call "bash" inside, because WSL (Windows Subsystem for Linux) brings an Ubuntu shell into Windows. When I type "bash" inside of your console window and hit enter. Nothing happens anymore. The cursor goes to the next line, I can type but nothing happens. So no it is unfortunately not possible to call another shell in your window.
